# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
            PersonalAccountBundle\Entity\User: bcrypt
    providers:
        database_users:
            entity: { class: PersonalAccountBundle:User, property: name }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
             anonymous: ~
             guard:
                 authenticators:
                     - app.form_authenticator
             logout:
                 path: /logout
                 target: /login
