# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.form_authenticator:
        class: PersonalAccountBundle\Security\FormAuthenticator
        arguments: ["@router", "@security.password_encoder","@doctrine.orm.entity_manager"]
        autowire: true
    app.google:
        class: PersonalAccountBundle\Service\Google
    app.attendance_manager:
        class: PersonalAccountBundle\Service\AttendanceManager
       #arguments: ["@doctrine.orm.entity_manager" ]
        autowire: true
    app.invoice_manager:
        class: PersonalAccountBundle\Service\InvoiceManager
        arguments: ["@doctrine.orm.entity_manager" ]
        autowire: true